baseURL = 'https://devjlopez.com/'

languageCode = 'en-us'
title        = 'DevJlopez'

googleAnalytics = 'G-D6MRVVBDW7'

builddrafts = true 

[params]
  favicon     = "img/devjlopez-favicon-color.png"
  description = "Learning great things by doing"
  keywords    = "Javier, DevJlopez, JavLopez, Golang, PHP, Python, Kubernetes, DevOps"

  ogLocale = "es_MX"
  themeColor = "#5540af"
  siteName = "DevJlopez"
  ogImage = "assets/img/social.jpg"
  twitterHandle = "@devjlopez"



  [params.author]
    name = 'Dev Javier Lopez'
