name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: Install Node.js (optional, if you have npm dependencies)
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Puedes ajustar la versión si es necesario
    
    - name: Build the site
      run: hugo --minify
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
