name: Deploy

on:
  push:
    branches:
      - main 
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    
    - name: Install Node.js (optional, if you have npm dependencies)
      uses: actions/setup-node@v3
      with:
        node-version: '16'
    
    - name: Build the site
      run: hugo --minify

    - name: Upload artifact for deployment
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public  # Carpeta generada por Hugo con los archivos estáticos

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write  # Permiso para escribir en GitHub Pages
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
